[tool.poetry]
name = "spanner-sqlalchemy-demo"
version = "0.1.0"
description = ""
authors = ["kazshinohara <kazshinohara@gcpx.org>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
uvicorn = "^0.18.2"
sqlalchemy-spanner = "^1.2.0"
SQLAlchemy-Utils = "^0.38.3"
alembic = "^1.8.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.961"
black = "^22.6.0"
isort = "^5.10.1"
pytest = "^7.1.2"
names = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
