[tool.poetry]
name = "spanner-sqlalchemy-demo"
version = "0.1.0"
description = ""
authors = ["kazshinohara <kazshinohara@gcpx.org>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.93.0"
uvicorn = "^0.20.0"
sqlalchemy-spanner = "^1.2.2"
SQLAlchemy-Utils = "^0.38.3"
alembic = "^1.8.1"
httpx = "^0.23.3"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
mypy = "^0.991"
black = "^23.1.0"
isort = "^5.10.1"
pytest = "^7.2.2"
names = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
